;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/11/23 星期六 18:21:34

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1017	1017	; Unity中文手册 Documentation.html
#define IDH_1000	1000	; 用户手册 Documentation\Manual\index.html
#define IDH_1018	1018	; 组件手册 Documentation\Components\index.html
#define IDH_1001	1001	; 脚本手册 Documentation\ScriptReference\index.html
#define IDH_1004	1004	; AccelerationEven 加速度事件 Documentation\ScriptReference\AccelerationEvent.html
#define IDH_1002	1002	; AccelerationEvent.acceleration 加速度 Documentation\ScriptReference\AccelerationEvent-acceleration.html
#define IDH_1003	1003	; AccelerationEvent.deltaTime 增量时间 Documentation\ScriptReference\AccelerationEvent-deltaTime.html
#define IDH_1005	1005	; CallbackOrderAttribute 回调命令属性 Documentation\ScriptReference\CallbackOrderAttribute.html
#define IDH_1006	1006	; CanEditMultipleObjects 多对象编辑 Documentation\ScriptReference\CanEditMultipleObjects.html
#define IDH_1008	1008	; CustomEditor 自定义编辑器 Documentation\ScriptReference\CustomEditor.html
#define IDH_1007	1007	; CustomEditor.CustomEditor 构造自定义编辑器 Documentation\ScriptReference\CustomEditor-ctor.html
#define IDH_1010	1010	; CustomPropertyDrawer 自定义属性抽屉 Documentation\ScriptReference\CustomPropertyDrawer.html
#define IDH_1009	1009	; CustomPropertyDrawer.CustomPropertyDrawer 构造自定义属性抽屉 Documentation\ScriptReference\CustomPropertyDrawer-ctor.html
#define IDH_1012	1012	; DrawGizmo 绘制辅助线框 Documentation\ScriptReference\DrawGizmo.html
#define IDH_1011	1011	; DrawGizmo.DrawGizmo 构造绘制辅助线框 Documentation\ScriptReference\DrawGizmo-ctor.html
#define IDH_1014	1014	; InitializeOnLoadAttribute 初始化加载属性 Documentation\ScriptReference\InitializeOnLoadAttribute.html
#define IDH_1016	1016	; MenuItem 菜单项 Documentation\ScriptReference\MenuItem.html
#define IDH_1015	1015	; MenuItem.MenuItem 构造菜单项 Documentation\ScriptReference\MenuItem-ctor.html
#define IDH_1024	1024	; PreferenceItem 首选项 Documentation\ScriptReference\PreferenceItem.html
#define IDH_1025	1025	; PreferenceItem.PreferenceItem 构造首选项 Documentation\ScriptReference\PreferenceItem-ctor.html
