;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/11/23 星期六 18:21:34

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1017=Documentation.html	; Unity中文手册
IDH_1000=Documentation\Manual\index.html	; 用户手册
IDH_1018=Documentation\Components\index.html	; 组件手册
IDH_1001=Documentation\ScriptReference\index.html	; 脚本手册
IDH_1004=Documentation\ScriptReference\AccelerationEvent.html	; AccelerationEven 加速度事件
IDH_1002=Documentation\ScriptReference\AccelerationEvent-acceleration.html	; AccelerationEvent.acceleration 加速度
IDH_1003=Documentation\ScriptReference\AccelerationEvent-deltaTime.html	; AccelerationEvent.deltaTime 增量时间
IDH_1005=Documentation\ScriptReference\CallbackOrderAttribute.html	; CallbackOrderAttribute 回调命令属性
IDH_1006=Documentation\ScriptReference\CanEditMultipleObjects.html	; CanEditMultipleObjects 多对象编辑
IDH_1008=Documentation\ScriptReference\CustomEditor.html	; CustomEditor 自定义编辑器
IDH_1007=Documentation\ScriptReference\CustomEditor-ctor.html	; CustomEditor.CustomEditor 构造自定义编辑器
IDH_1010=Documentation\ScriptReference\CustomPropertyDrawer.html	; CustomPropertyDrawer 自定义属性抽屉
IDH_1009=Documentation\ScriptReference\CustomPropertyDrawer-ctor.html	; CustomPropertyDrawer.CustomPropertyDrawer 构造自定义属性抽屉
IDH_1012=Documentation\ScriptReference\DrawGizmo.html	; DrawGizmo 绘制辅助线框
IDH_1011=Documentation\ScriptReference\DrawGizmo-ctor.html	; DrawGizmo.DrawGizmo 构造绘制辅助线框
IDH_1014=Documentation\ScriptReference\InitializeOnLoadAttribute.html	; InitializeOnLoadAttribute 初始化加载属性
IDH_1016=Documentation\ScriptReference\MenuItem.html	; MenuItem 菜单项
IDH_1015=Documentation\ScriptReference\MenuItem-ctor.html	; MenuItem.MenuItem 构造菜单项
IDH_1024=Documentation\ScriptReference\PreferenceItem.html	; PreferenceItem 首选项
IDH_1025=Documentation\ScriptReference\PreferenceItem-ctor.html	; PreferenceItem.PreferenceItem 构造首选项
